/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package core;

import utilities.LineStatus;

/**
 * This class represents production line.
 * @author Lukas
 */
public class Line
{

    private String lineID;
    private final LineStatus lineStatus;

    /**
     * Two argument constructor
     * @param lid the line's ID
     * @param ls the line's status
     */
    public Line(String lid, LineStatus ls)
    {
        this.lineID = lid;
        this.lineStatus = ls;
    }

    public LineStatus getLineStatus()
    {
        return lineStatus;
    }

    public String getLineID()
    {
        return lineID;
    }

    public void setLineID(String lineID)
    {
        this.lineID = lineID;
    }

}
