/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package core;

import utilities.RequestType;

/**
 * This class represents the requests 
 * that can be initiated by the user
 * if the support is required to
 * resolve an issue.
 * @author Lukas
 */
public class Request
{

    private String requestID = "r01";
    private String requestTime;
    private String lineID;
    private String areaID;
    private String issue;
    private RequestType reqType;

    /**
     * Constructor which includes all
     * arguments except the issue which
     * is expected to be a long String and
     * therefore should be initiated separately.
     * @param rid new request id
     * @param time time when the request was made
     * @param lid the id of the line for which support is required
     * @param area the id of the area for which support is required
     * @param rt the type of support required
     */
    public Request(String rid, String time, String lid, String area,
            RequestType rt)
    {
        this.areaID = area;
        this.lineID = lid;
        this.reqType = rt;
        this.requestID = rid;
        this.requestTime = time;
    }

    public String getRequestID()
    {
        return requestID;
    }

    public void setRequestID(String requestID)
    {
        this.requestID = requestID;
    }

    public String getRequestTime()
    {
        return requestTime;
    }

    public void setRequestTime(String requestTime)
    {
        this.requestTime = requestTime;
    }

    public String getLineID()
    {
        return lineID;
    }

    public void setLineID(String lineID)
    {
        this.lineID = lineID;
    }

    public String getAreaID()
    {
        return areaID;
    }

    public void setAreaID(String areaID)
    {
        this.areaID = areaID;
    }

    public String getIssue()
    {
        return issue;
    }

    public void setIssue(String issue)
    {
        this.issue = issue;
    }

    public RequestType getReqType()
    {
        return reqType;
    }

    public void setReqType(RequestType reqType)
    {
        this.reqType = reqType;
    }

    
}
