/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package core;

/**
 * This class represents the shift.
 * In the final application it will
 * orchestrate other classes available within the core
 * package. Currently this class is not used.
 * @author Lukasz Chlodnicki
 */
public class Shift
{
    private String startTime; //the start time of the Shift

    public String getStartTime()
    {
        return startTime;
    }

    public void setStartTime(String startTime)
    {
        this.startTime = startTime;
    }
    
    public Shift(String st){
        this.startTime = st;
    }
}
