/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package core;

import utilities.Roles;

/**
 * This class represents the user
 * of the system.
 * @author Lukas
 */
public class User
{

    private Roles role;
    private String name;

    /**
     * Two argument constructor for the user
     * 
     * @param rol represents user's role of
     * the enumerated class Roles
     * @param nm represents user's name
    */
    public User(Roles rol, String nm)
    {
        this.role = rol;
        this.name = nm;
    }

    public Roles getRole()
    {
        return role;
    }

    public void setRole(Roles role)
    {
        this.role = role;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }
    
}
