/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package core;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author Lukas
 */
public class StoppageTest
{
    
    public StoppageTest()
    {
    }
    
    @BeforeClass
    public static void setUpClass()
    {
    }
    
    @AfterClass
    public static void tearDownClass()
    {
    }
    
    @Before
    public void setUp()
    {
    }
    
    @After
    public void tearDown()
    {
    }

    /**
     * Test of getStoppageID method, of class Stoppage.
     */
    @Test
    public void testGetStoppageID()
    {
        System.out.println("getStoppageID");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getStoppageID();
        assertEquals(expResult, result);

    }

    /**
     * Test of setStoppageID method, of class Stoppage.
     */
    @Test
    public void testSetStoppageID()
    {
        System.out.println("setStoppageID");
        String stoppageID = "";
        Stoppage instance = new Stoppage();
        instance.setStoppageID(stoppageID);
     
    }

    /**
     * Test of getLineID method, of class Stoppage.
     */
    @Test
    public void testGetLineID()
    {
        System.out.println("getLineID");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getLineID();
        assertEquals(expResult, result);
   
    }

    /**
     * Test of setLineID method, of class Stoppage.
     */
    @Test
    public void testSetLineID()
    {
        System.out.println("setLineID");
        String lineID = "";
        Stoppage instance = new Stoppage();
        instance.setLineID(lineID);
    
    }

    /**
     * Test of getAreaID method, of class Stoppage.
     */
    @Test
    public void testGetAreaID()
    {
        System.out.println("getAreaID");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getAreaID();
        assertEquals(expResult, result);

    }

    /**
     * Test of setAreaID method, of class Stoppage.
     */
    @Test
    public void testSetAreaID()
    {
        System.out.println("setAreaID");
        String areaID = "";
        Stoppage instance = new Stoppage();
        instance.setAreaID(areaID);
      
    }

    /**
     * Test of getStartTime method, of class Stoppage.
     */
    @Test
    public void testGetStartTime()
    {
        System.out.println("getStartTime");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getStartTime();
        assertEquals(expResult, result);

    }

    /**
     * Test of setStartTime method, of class Stoppage.
     */
    @Test
    public void testSetStartTime()
    {
        System.out.println("setStartTime");
        String startTime = "";
        Stoppage instance = new Stoppage();
        instance.setStartTime(startTime);
     
    }

    /**
     * Test of getEndTime method, of class Stoppage.
     */
    @Test
    public void testGetEndTime()
    {
        System.out.println("getEndTime");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getEndTime();
        assertEquals(expResult, result);
    
    }

    /**
     * Test of setEndTime method, of class Stoppage.
     */
    @Test
    public void testSetEndTime()
    {
        System.out.println("setEndTime");
        String endTime = "";
        Stoppage instance = new Stoppage();
        instance.setEndTime(endTime);
      
    }

    /**
     * Test of getDuration method, of class Stoppage.
     */
    @Test
    public void testGetDuration()
    {
        System.out.println("getDuration");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getDuration();
        assertEquals(expResult, result);
       
    }

    /**
     * Test of setDuration method, of class Stoppage.
     */
    @Test
    public void testSetDuration()
    {
        System.out.println("setDuration");
        String duration = "";
        Stoppage instance = new Stoppage();
        instance.setDuration(duration);
        
    }

    /**
     * Test of getDescription method, of class Stoppage.
     */
    @Test
    public void testGetDescription()
    {
        System.out.println("getDescription");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getDescription();
        assertEquals(expResult, result);
        
    }

    /**
     * Test of setDescription method, of class Stoppage.
     */
    @Test
    public void testSetDescription()
    {
        System.out.println("setDescription");
        String description = "";
        Stoppage instance = new Stoppage();
        instance.setDescription(description);
        
    }

    /**
     * Test of getOccurencies method, of class Stoppage.
     */
    @Test
    public void testGetOccurencies()
    {
        System.out.println("getOccurencies");
        Stoppage instance = new Stoppage();
        int expResult = 0;
        int result = instance.getOccurencies();
        assertEquals(expResult, result);
       
    }

    /**
     * Test of setOccurencies method, of class Stoppage.
     */
    @Test
    public void testSetOccurencies()
    {
        System.out.println("setOccurencies");
        int occurencies = 0;
        Stoppage instance = new Stoppage();
        instance.setOccurencies(occurencies);
       
    }

    /**
     * Test of getSolution method, of class Stoppage.
     */
    @Test
    public void testGetSolution()
    {
        System.out.println("getSolution");
        Stoppage instance = new Stoppage();
        String expResult = "";
        String result = instance.getSolution();
        assertEquals(expResult, result);
        
    }

    /**
     * Test of setSolution method, of class Stoppage.
     */
    @Test
    public void testSetSolution()
    {
        System.out.println("setSolution");
        String solution = "";
        Stoppage instance = new Stoppage();
        instance.setSolution(solution);
   
    }
    
}
