/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package beans;

import java.beans.PropertyChangeSupport;
import javax.faces.event.ValueChangeEvent;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author Lukas
 */
public class DataBeanTest
{
    
    public DataBeanTest()
    {
    }
    
    @BeforeClass
    public static void setUpClass()
    {
    }
    
    @AfterClass
    public static void tearDownClass()
    {
    }
    
    @Before
    public void setUp()
    {
    }
    
    @After
    public void tearDown()
    {
    }

    /**
     * Test of getCurrentStatus method, of class DataBean.
     */
    @Test
    public void testGetCurrentStatus()
    {
        System.out.println("getCurrentStatus");
        DataBean instance = new DataBean();
        String expResult = "";
        String result = instance.getCurrentStatus();
        assertEquals(expResult, result);
        
    }

    /**
     * Test of setCurrentStatus method, of class DataBean.
     */
    @Test
    public void testSetCurrentStatus()
    {
        System.out.println("setCurrentStatus");
        String currentStatus = "";
        DataBean instance = new DataBean();
        instance.setCurrentStatus(currentStatus);
        
    }

    /**
     * Test of getLineStatus method, of class DataBean.
     */
    @Test
    public void testGetLineStatus()
    {
        System.out.println("getLineStatus");
        DataBean instance = new DataBean();
        String expResult = "";
        String result = instance.getLineStatus();
        assertEquals(expResult, result);
     
    }

    /**
     * Test of setLineStatus method, of class DataBean.
     */
    @Test
    public void testSetLineStatus()
    {
        System.out.println("setLineStatus");
        String lineStatus = "";
        DataBean instance = new DataBean();
        instance.setLineStatus(lineStatus);
      
    }

    /**
     * Test of getLine method, of class DataBean.
     */
    @Test
    public void testGetLine()
    {
        System.out.println("getLine");
        DataBean instance = new DataBean();
        String expResult = "";
        String result = instance.getLine();
        assertEquals(expResult, result);
      
    }

    /**
     * Test of setLine method, of class DataBean.
     */
    @Test
    public void testSetLine()
    {
        System.out.println("setLine");
        String line = "";
        DataBean instance = new DataBean();
        instance.setLine(line);
    
    }

    /**
     * Test of getPropertySupport method, of class DataBean.
     */
    @Test
    public void testGetPropertySupport()
    {
        System.out.println("getPropertySupport");
        DataBean instance = new DataBean();
        PropertyChangeSupport expResult = null;
        PropertyChangeSupport result = instance.getPropertySupport();
        assertEquals(expResult, result);
     
    }

    /**
     * Test of setPropertySupport method, of class DataBean.
     */
    @Test
    public void testSetPropertySupport()
    {
        System.out.println("setPropertySupport");
        PropertyChangeSupport propertySupport = null;
        DataBean instance = new DataBean();
        instance.setPropertySupport(propertySupport);

    }

    /**
     * Test of getQueryResult method, of class DataBean.
     */
    @Test
    public void testGetQueryResult()
    {
        System.out.println("getQueryResult");
        DataBean instance = new DataBean();
        String expResult = "";
        String result = instance.getQueryResult();
        assertEquals(expResult, result);
       
    }

    /**
     * Test of setQueryResult method, of class DataBean.
     */
    @Test
    public void testSetQueryResult()
    {
        System.out.println("setQueryResult");
        String queryResult = "";
        DataBean instance = new DataBean();
        instance.setQueryResult(queryResult);
     
    }

    /**
     * Test of getCurrLine method, of class DataBean.
     */
    @Test
    public void testGetCurrLine()
    {
        System.out.println("getCurrLine");
        DataBean instance = new DataBean();
        String expResult = "";
        String result = instance.getCurrLine();
        assertEquals(expResult, result);
      
    }

    /**
     * Test of setCurrLine method, of class DataBean.
     */
    @Test
    public void testSetCurrLine()
    {
        System.out.println("setCurrLine");
        String currLine = "";
        DataBean instance = new DataBean();
        instance.setCurrLine(currLine);
    
    }

    /**
     * Test of updateLineStatus method, of class DataBean.
     */
    @Test
    public void testUpdateLineStatus() throws Exception
    {
        System.out.println("updateLineStatus");
        String lineNumber = "";
        DataBean instance = new DataBean();
        instance.updateLineStatus(lineNumber);
      
    }

    /**
     * Test of updateCurrentLine method, of class DataBean.
     */
    @Test
    public void testUpdateCurrentLine()
    {
        String result = "";
        System.out.println("updateCurrentLine");
        DataBean instance = new DataBean();
        String expResult = "";
        result = instance.updateCurrentLine();
        assertEquals(expResult, result);
        
    }

    /**
     * Test of lineChanged method, of class DataBean.
     */
    @Test
    public void testLineChanged() throws Exception
    {
        System.out.println("lineChanged");
        ValueChangeEvent vcl = null;
        DataBean instance = new DataBean();
        instance.lineChanged(vcl);
      
    }
    
}
