/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package utilities;

/**
 * This enum specifies area
 * names.
 * (Not yet used)
 * @author Lukasz Chlodnicki
 */
public enum AreaNames
{
    Bottle_blower,
    Filler,
    Labeler,
    Case_packer,
    Palletiser;
}
