/*
 * Feel free to edit, copy and reuse the resources
 * available in this project, unless you are going to use autogenerated
 * code where different licences might apply. It is your responsibility
 * to ensure that you posses the right to modify, copy or reuse such 
 * resources.
 */
package beans;

import core.Request;
import java.io.Serializable;
import javax.annotation.ManagedBean;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import utilities.RequestType;

/**
 * This class is responsible for
 * creation of the new message or request.
 * @author Lukasz Chlodnicki
 */
@Named
@ManagedBean
@SessionScoped
public class MessageBean implements Serializable
{

    private String requestID = "";
    private String requestTime = "";
    private String lineID = "";
    private String areaID = "";
    private String issue = "";
    private RequestType reqType;
    private Request request;
    
    public Request getRequest()
    {
        return request;
    }
    
    public void setRequest(Request request)
    {
        this.request = request;
    }
    
    public String getRequestID()
    {
        return requestID;
    }
    
    public void setRequestID(String requestID)
    {
        this.requestID = requestID;
    }
    
    public String getRequestTime()
    {
        return requestTime;
    }
    
    public void setRequestTime(String requestTime)
    {
        this.requestTime = requestTime;
    }
    
    public String getLineID()
    {
        return lineID;
    }
    
    public void setLineID(String lineID)
    {
        this.lineID = lineID;
    }
    
    public String getAreaID()
    {
        return areaID;
    }
    
    public void setAreaID(String areaID)
    {
        this.areaID = areaID;
    }
    
    public String getIssue()
    {
        return issue;
    }
    
    public void setIssue(String issue)
    {
        this.issue = issue;
    }
    
    public RequestType getReqType()
    {
        return reqType;
    }
    
    public void setReqType(RequestType reqType)
    {
        this.reqType = reqType;
    }
    
    /**
     * Method that creates a new request.
     * @param rid the request ID
     * @param time the request time
     * @param lid the line's ID for which the request is made
     * @param area the area name for which the request is made
     * @param rt the request recipient enumerated type: MTL, SOM, ENGINEER or ELECTRICIAN 
    */
    public void makeRequest(String rid, String time, String lid, String area,
            RequestType rt)
    {
        this.setRequest(new Request(rid, time, lid, area, rt));
        System.out.println("new request " + rid + " made at " + time + " for line " + lid
        + " " + area + " required support from " + rt);
    }
}
